<a href="https://colab.research.google.com/github/sugban/Personal-projects/blob/main/BINGO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [229]:
import random
import numpy as np

In [230]:
word1 = ['sun','right','I','one','Buy','Tie','Die','know','whole']
word2 = ['son','write','Eye','Won','Bye','Tye','Dye','No','Hole']
pair = []
for i in range(10):
    pair.append(random.choice(word1))
    pair.append(random.choice(word2))

print(pair)

['one', 'write', 'right', 'Eye', 'whole', 'No', 'Tie', 'Hole', 'I', 'write', 'Tie', 'son', 'Buy', 'Tye', 'one', 'Dye', 'Die', 'Dye', 'one', 'Tye']


In [231]:
from numpy import random

x = random.randint(1,100, size=(4, 5))

x= np.sort(x)
y =np.array([[pair[:5]],[pair[5:10]],[pair[10:15]],[pair[15:20]]])
print(x)
print(y)

[[19 41 50 77 91]
 [ 3 13 24 67 97]
 [ 9 12 28 73 86]
 [51 56 65 70 89]]
[[['one' 'write' 'right' 'Eye' 'whole']]

 [['No' 'Tie' 'Hole' 'I' 'write']]

 [['Tie' 'son' 'Buy' 'Tye' 'one']]

 [['Dye' 'Die' 'Dye' 'one' 'Tye']]]


In [232]:
print(x.shape)
x = x.reshape((x.shape[0], x.shape[1], 1))
print(x.shape)
print(y.shape)

(4, 5)
(4, 5, 1)
(4, 1, 5)


In [233]:
x = x.reshape(4,1,5)
print(x.shape)
print(y.shape)


(4, 1, 5)
(4, 1, 5)


In [234]:
slip = np.hstack((x, y))
print(slip)

[[['19' '41' '50' '77' '91']
  ['one' 'write' 'right' 'Eye' 'whole']]

 [['3' '13' '24' '67' '97']
  ['No' 'Tie' 'Hole' 'I' 'write']]

 [['9' '12' '28' '73' '86']
  ['Tie' 'son' 'Buy' 'Tye' 'one']]

 [['51' '56' '65' '70' '89']
  ['Dye' 'Die' 'Dye' 'one' 'Tye']]]


In [235]:
print(slip.shape)
newarr = slip.reshape(8,5*1)
print(newarr)

(4, 2, 5)
[['19' '41' '50' '77' '91']
 ['one' 'write' 'right' 'Eye' 'whole']
 ['3' '13' '24' '67' '97']
 ['No' 'Tie' 'Hole' 'I' 'write']
 ['9' '12' '28' '73' '86']
 ['Tie' 'son' 'Buy' 'Tye' 'one']
 ['51' '56' '65' '70' '89']
 ['Dye' 'Die' 'Dye' 'one' 'Tye']]


In [236]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [237]:
#!ls "/content/drive/My Drive"

In [240]:
df = pd.DataFrame(data = newarr)
df.set_index(0).to_excel('/content/drive/My Drive/Bingo.xlsx')

In [241]:
df = pd.read_excel('/content/drive/My Drive/Bingo.xlsx')
df

Unnamed: 0      1      2    3      4
0         19     41     50   77     91
1        one  write  right  Eye  whole
2          3     13     24   67     97
3         No    Tie   Hole    I  write
4          9     12     28   73     86
5        Tie    son    Buy  Tye    one
6         51     56     65   70     89
7        Dye    Die    Dye  one    Tye